AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

Globals:
  Function:
    Timeout: 3

Resources:
  branchcreate:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda_handler
      CodeUri: src/functions/branch_functions
      Handler: branch_create.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          databaseName: ReferenceData
          databaseUrl: http://host.docker.internal:8000
      Events:
        Api:
          Type: Api
          Properties:
            Path: /branchcreate
            Method: post

  branchread:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda_handler
      CodeUri: src/functions/branch_functions
      Handler: branch_read.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          databaseUrl: http://host.docker.internal:8000
      Events:
        Api:
          Type: Api
          Properties:
            Path: /branchread
            Method: get

  branchupdate:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda_handler
      CodeUri: src/functions/branch_functions
      Handler: branch_update.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          databaseUrl: http://host.docker.internal:8000
      Events:
        Api:
          Type: Api
          Properties:
            Path: /branchupdate
            Method: put

  branchdelete:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda_handler
      CodeUri: src/functions/branch_functions
      Handler: branch_delete.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          databaseUrl: http://host.docker.internal:8000
      Events:
        Api:
          Type: Api
          Properties:
            Path: /branchdelete
            Method: delete

  branchlistall:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda_handler
      CodeUri: src/functions/branch_functions
      Handler: branch_list.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          databaseUrl: http://host.docker.internal:8000
      Events:
        Api:
          Type: Api
          Properties:
            Path: /branchlistall
            Method: get

  dealercreate:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda_handler
      CodeUri: src/functions/dealer_functions
      Handler: dealer_create.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          databaseUrl: http://host.docker.internal:8000
      Events:
        Api:
          Type: Api
          Properties:
            Path: /dealercreate
            Method: post

  dealerread:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda_handler
      CodeUri: src/functions/dealer_functions
      Handler: dealer_read.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          databaseUrl: http://host.docker.internal:8000
      Events:
        Api:
          Type: Api
          Properties:
            Path: /dealerread
            Method: get

  dealerupdate:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda_handler
      CodeUri: src/functions/dealer_functions
      Handler: dealer_update.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          databaseUrl: http://host.docker.internal:8000
      Events:
        Api:
          Type: Api
          Properties:
            Path: /dealerupdate
            Method: put

  dealerdelete:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda_handler
      CodeUri: src/functions/dealer_functions
      Handler: dealer_delete.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          databaseUrl: http://host.docker.internal:8000
      Events:
        Api:
          Type: Api
          Properties:
            Path: /dealerdelete
            Method: delete

  dealerlistall:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda_handler
      CodeUri: src/functions/dealer_functions
      Handler: dealer_list.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          databaseUrl: http://host.docker.internal:8000
      Events:
        Api:
          Type: Api
          Properties:
            Path: /dealerlistall
            Method: get

  gendercreate:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda_handler
      CodeUri: src/functions/gender_functions
      Handler: gender_create.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          databaseUrl: http://host.docker.internal:8000
      Events:
        Api:
          Type: Api
          Properties:
            Path: /gendercreate
            Method: post

  genderread:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda_handler
      CodeUri: src/functions/gender_functions
      Handler: gender_read.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          databaseUrl: http://host.docker.internal:8000
      Events:
        Api:
          Type: Api
          Properties:
            Path: /genderread
            Method: get

  genderupdate:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda_handler
      CodeUri: src/functions/gender_functions
      Handler: gender_update.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          databaseUrl: http://host.docker.internal:8000
      Events:
        Api:
          Type: Api
          Properties:
            Path: /genderupdate
            Method: put

  genderdelete:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda_handler
      CodeUri: src/functions/gender_functions
      Handler: gender_delete.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          databaseUrl: http://host.docker.internal:8000
      Events:
        Api:
          Type: Api
          Properties:
            Path: /genderdelete
            Method: delete

  genderlistall:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda_handler
      CodeUri: src/functions/gender_functions
      Handler: gender_list.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          databaseUrl: http://host.docker.internal:8000
      Events:
        Api:
          Type: Api
          Properties:
            Path: /genderlistall
            Method: get